[package]
name = "iterator"
version = "0.1.0"
authors = ["Antoine Pouillaude <a.pouillaude@criteo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
